#!/bin/bash

echo "🔍 Universal Element Locator - Intermittent Issue Debug"
echo "====================================================="

echo "🐛 Issue: Works first time, fails second time"
echo ""
echo "🔧 Enhanced debugging added:"
echo "   • Content script logs injection state"
echo "   • Content script logs elements with IDs, classes, data attributes" 
echo "   • Content script logs locator counts for first 5 elements"
echo "   • Content script logs final scan summary"
echo "   • Popup logs scan response details"
echo "   • Popup logs what's being saved to storage"
echo "   • Added storage.clear() before saving new results"
echo ""
echo "🧪 Testing Steps for Intermittent Issue:"
echo "   1. Load extension in Chrome"
echo "   2. Open test page (e.g., test-results-fix.html)"
echo "   3. Open DevTools (F12) and go to Console tab"
echo "   4. Run FIRST scan - note all console messages"
echo "   5. Run SECOND scan - note differences in console"
echo "   6. Compare the debug output between scans"
echo ""
echo "🔍 Key Debug Messages to Watch:"
echo "   CONTENT SCRIPT:"
echo "   • '🔍 Content: Starting page scan...'"
echo "   • '🔍 Content: Window injection state: true/false'"
echo "   • '🔍 Content: Found element with ID: ...'"
echo "   • '🔍 Content: Element 0 (tagname) locators: {...}'"
echo "   • '🔍 Content: Scan complete! {...}'"
echo ""
echo "   POPUP SCRIPT:"
echo "   • '🔍 Popup: Scan response received: {...}'"
echo "   • '🔍 Popup: Saving scan data: {...}'"
echo ""
echo "   RESULTS SCRIPT:"
echo "   • '🔍 Debug: Raw storage result: {...}'"
echo "   • '🔍 Debug: createLocatorsList called with: [...], type'"
echo ""
echo "💡 Expected Behavior:"
echo "   • FIRST scan: Should see locators being created and displayed"
echo "   • SECOND scan: Should behave identically to first scan"
echo ""
echo "❌ If Issue Persists:"
echo "   • Check if content script injection state changes"
echo "   • Verify locator creation in content script"
echo "   • Confirm storage data consistency"
echo "   • Look for any error messages between scans"
