#!/bin/bash

# Test Element Capture - Comprehensive Analysis
echo "🔍 Testing Element Capture and Highlighting..."
echo "=========================================="

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Start Chrome with extension and test page
echo "📱 Opening test page..."
open -a "Google Chrome" --args --load-extension="$SCRIPT_DIR" "file://$SCRIPT_DIR/test-element-capture.html"

echo ""
echo "🔍 MANUAL TESTING STEPS:"
echo "========================"
echo "1. Open Chrome DevTools (F12)"
echo "2. Go to Console tab"
echo "3. Click the extension icon and perform 'Scan with Highlighting'"
echo "4. Watch the console for element highlighting messages"
echo "5. After scan completes, run: getHighlightSummary()"
echo "6. Check if 'visual_user' link is highlighted (should be green)"
echo "7. Verify all expected elements are captured in the results"
echo ""
echo "🔍 DEBUGGING STEPS:"
echo "==================="
echo "In Console, you can also run these debug commands:"
echo ""
echo "// Check if specific elements are visible"
echo "document.querySelector('.visual-user-link')"
echo "getComputedStyle(document.querySelector('.visual-user-link'))"
echo ""
echo "// Manual visibility check"
echo "const el = document.querySelector('.visual-user-link');"
echo "console.log('Element:', el);"
echo "console.log('Visible:', el && el.offsetParent !== null);"
echo "console.log('Display:', getComputedStyle(el).display);"
echo "console.log('Visibility:', getComputedStyle(el).visibility);"
echo "console.log('BoundingRect:', el.getBoundingClientRect());"
echo ""
echo "// Check all links"
echo "document.querySelectorAll('a').forEach((link, i) => {"
echo "  console.log(\`Link \${i+1}:\`, link.textContent.trim(), link.href);"
echo "});"
echo ""
echo "📋 Expected Results:"
echo "==================="
echo "- All visible links should be highlighted (including 'visual_user')"
echo "- All buttons should be highlighted"
echo "- All form inputs should be highlighted"
echo "- Total highlighted count should match visible interactive elements"
echo "- Extension results should show comprehensive element data"
echo ""
echo "🚨 If elements are missing:"
echo "=========================="
echo "1. Check console for 'Skipped by tag' messages"
echo "2. Look for visibility filtering issues"
echo "3. Verify element collection traversal is working"
echo "4. Check if highlighting function is being called for all elements"

sleep 2
echo ""
echo "✅ Test environment ready. Please follow the manual testing steps above."
