#!/bin/bash

# Text Content Display Fix Test
# Test the extension's ability to display proper text content instead of [object Object]

set -e
cd "$(dirname "$0")"

echo "📝 Text Content Display Fix Test"
echo "================================"

echo "🧪 Testing Instructions:"
echo "========================"
echo ""
echo "1. RELOAD THE EXTENSION:"
echo "   - Go to chrome://extensions/"
echo "   - Find 'Universal Element Locator'"
echo "   - Click the reload button (circular arrow)"
echo ""
echo "2. OPEN A TEST PAGE WITH TEXT CONTENT:"
echo "   - Navigate to any webpage with text elements (buttons, links, headings, paragraphs)"
echo "   - For example: file://$(pwd)/unique-selector-test.html"
echo "   - Or any regular website like https://example.com"
echo ""
echo "3. SCAN THE PAGE:"
echo "   - Click the Universal Element Locator extension icon"
echo "   - Click 'Scan Page Elements'"
echo "   - Wait for the scan to complete"
echo ""
echo "4. VIEW RESULTS AND CHECK TEXT CONTENT:"
echo "   - Click 'View Scanned Results'"
echo "   - Look at the 'TEXT CONTENT' column in the results table"
echo ""
echo "🔍 What to Look For:"
echo "==================="
echo ""
echo "✅ BEFORE THE FIX (PROBLEMS):"
echo "   ❌ TEXT CONTENT column showed: [object Object]"
echo "   ❌ No actual text content visible"
echo "   ❌ Unable to see element text for identification"
echo ""
echo "✅ AFTER THE FIX (EXPECTED):"
echo "   ✅ TEXT CONTENT column shows actual element text"
echo "   ✅ Button text: 'Submit', 'Cancel', 'Actions', etc."
echo "   ✅ Link text: 'Home', 'About', 'Contact', etc."
echo "   ✅ Heading text: 'Welcome', 'Features', 'News', etc."
echo "   ✅ Paragraph snippets with proper truncation"
echo "   ✅ 'No text content' for empty elements (divs, spans without text)"
echo ""
echo "📋 SPECIFIC EXAMPLES TO VERIFY:"
echo "==============================="
echo ""
echo "1. BUTTONS WITH TEXT:"
echo "   - Should show button label text (e.g., 'Actions', 'Submit')"
echo "   - Truncated at 40 characters with '...' if longer"
echo "   - Hover tooltip shows full text"
echo ""
echo "2. LINKS WITH TEXT:"
echo "   - Should show link text content"
echo "   - Not just 'a' tag, but actual clickable text"
echo ""
echo "3. HEADINGS:"
echo "   - H1, H2, H3 elements should show their text content"
echo "   - Section titles and page headings visible"
echo ""
echo "4. EMPTY ELEMENTS:"
echo "   - DIVs and SPANs without text should show 'No text content'"
echo "   - Proper handling of whitespace-only elements"
echo ""
echo "5. TRUNCATION:"
echo "   - Long text content should be truncated at 40 characters"
echo "   - Should end with '...' when truncated"
echo "   - Full text available in tooltip on hover"
echo ""
echo "🔧 Debugging Information:"
echo "========================="
echo ""
echo "The fix addresses the textContent object structure:"
echo "- content.js stores: { innerText: '...', textContent: '...', cleanText: '...', hasText: true/false }"
echo "- results.js now properly extracts text from this object structure"
echo "- Prioritizes cleanText > innerText > textContent for best display"
echo ""
echo "🚀 Success Criteria:"
echo "==================="
echo "   ✅ No more '[object Object]' in TEXT CONTENT column"
echo "   ✅ Actual readable text content displayed"
echo "   ✅ Proper truncation for long text (40 chars + '...')"
echo "   ✅ 'No text content' for truly empty elements"
echo "   ✅ Tooltips show full text on hover"
echo "   ✅ Clean, readable text content helps with element identification"
echo ""
echo "Ready to test text content display! 📝"
